Description of get_subjid
get_subjid
PURPOSE
SYNOPSIS
function [ subjid ] = get_subjid(config, nS, treat)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
get_cons_path GET_CONS_PATH Summary of this function goes here
extract_betas
preprocessing
run_first_level
SOURCE CODE
function [ subjid ] = get_subjid(config, nS, treat)
import utils.Var;
if ~exist('treat', 'var'); treat = true; end;
%GET_SUBJID returns the right name for the subj
if isnumeric(nS)
    name_subj = sprintf( '%s%03i', config.subj_prefix, nS );
else
    name_subj = nS{1};
    treat = 0;
end
sdirs = dir(fullfile(config.raw_base, [name_subj '*']));
if ~treat || Var.get(config, 'subjid_complete', false)
    subjid = sdirs(1).name;
elseif iscell(Var.get(config, 'subjs_labels', false))
    pos = config.subjs == nS;
    subjid = config.subjs_labels{pos};
elseif iscell(Var.get(config, 'subjs', false))
    subjid = config.subjs{nS};
else
    subjid = name_subj;
end
end