function bids = BIDS_struct

bids = struct( ...
    ... % ANATATOMICAL
    'anat_dir', 'anat', ...
    'anat_modality', 'T1w', ...
    ... % DIFFUSION
    'dwi_dir', 'dwi', ...
    ... % FIELD MAPPING
    'fmap_dir', 'fmap', ...
    ... % FUNCTIONAL
    'func_dir', 'func' ...
);